default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"]%>
  socket: <%= ENV["DATABASE_SOCKET"]%>

development:
  <<: *default
  database: AWScheduleDB

test:
  <<: *default
  database: AWScheduleDB

production:
  <<: *default
  database: AWScheduleDB
